### ISSUE TITLE
Upgrade New Relic Java Agent to v4.9.0

### ISSUE THREAD

**Issue by dlehammer** [agorapulse/grails-newrelic#10]
New Relic Java Agent [v4.9.0](https://docs.newrelic.com/docs/release-notes/agent-release-notes/java-release-notes/java-agent-490) was released 2018-12-18.

It would be sensible to [upgrade](https://github.com/agorapulse/grails-newrelic/blob/master/gradle.properties) this plugin to match.

**Comment by musketyr** [comment]
this is already done. thank you for updating the docs
