### ISSUE TITLE
Question: Plugin only works with Java 1.8?

### ISSUE THREAD

**Issue by orkonano** [agorapulse/grails-newrelic#2]
I'm installing the plugin in my project with this setting:

| Grails Version: 3.1.6
| Groovy Version: 2.4.6
| JVM Version: 1.7.0_80
| NewRelic plugin version: 3.28.0

When I try to run/test the app I get the following error:

> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsApplicationPostProcessor': Initialization of bean failed; nested exception is java.lang.UnsupportedClassVersionError: grails/newrelic/NewrelicGrailsPlugin : Unsupported major.minor version 52.0

My question is if the plugin only works with java 1.8

**Comment by benorama** [comment]
Theoretically, it should run with 1.7.
But we only use it with java 1.8.
You might try to re-build the plugin locally to see if it solve your issue:
- download the repo,
- change the version to 3.28.0-SNAPSHOT
- run grails install

And try to use it locally in one of your Grails app.

**Comment by orkonano** [comment]
@benorama I rebuilt the plugin locally with Java 1.7 and the app was compiled without trouble.
Are you going to upload to _bintray_ the plugin to work with Java 1.7? Please Let me know if I could help you.

Thanks
