### ISSUE TITLE
 Instrumentation problem - /org.grails.web.mapping.mvc.GrailsControllerUrlMappingInfo

### ISSUE THREAD

**Issue by ajcann** [agorapulse/grails-newrelic#3]
We're seeing /org.grails.web.mapping.mvc.GrailsControllerUrlMappingInfo for many entries where an underlying service or controller is acting. I understand this to be a instrumentation issue - is there any general way to solve this issue?

**Comment by benorama** [comment]
Are you taking about the Transactions area of NewRelic?

Did you try to set `enable_auto_transaction_naming` to false in your new relic.yml config file?
https://docs.newrelic.com/docs/agents/java-agent/configuration/java-agent-configuration-config-file

**Comment by ajcann** [comment]
Yes, that's correct. I did set this parameter to false, which helped to some extent (the controller/service endpoints appeared), but the vast majority of calls still just appear as a huge blocks of urlmappinginfo. That is, it looks like those urlmappinginfo is a very slow process whereas I know that time is being spent in specific controllers.

**Comment by ghost** [comment]
I believe is not a problem of the plugin. Instead, Grails 3 is not well supported in NewRelic 

See https://discuss.newrelic.com/t/grails-3-support/37362

**Comment by ajcann** [comment]
Yep - that's the problem indeed. I guess I thought the plugin offered the
missing instrumentation. Thank you for you help.

**Comment by musketyr** [comment]
@ajcann what is the status of this issue? do you still face problems with the latest version?

**Comment by ajcann** [comment]
@musketyr Hah - well I think we sorted out some work around in 2016 :)

**Comment by alexleonovhs1** [comment]
@ajcann what was your workaround? I’m looking at the same problem and thinking about custom instrumentation :)

**Comment by ajcann** [comment]
> @ajcann what was your workaround? I’m looking at the same problem and thinking about custom instrumentation :)

Sorry @alexleonovhs1 it's been 4 years since I've last seen that codebase and I do not recall.

**Comment by alexleonovhs1** [comment]
@ajcann thanks for getting back anyway
